/*
LangGraph Platform

Testing AssistantsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package langgraphgo_test

import (
	"context"
	"testing"

	"github.com/chelala/langgraphgo"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_langgraphgo_AssistantsAPIService(t *testing.T) {

	configuration := langgraphgo.NewConfiguration()
	configuration.Servers = langgraphgo.ServerConfigurations{
		{
			URL:         "http://127.0.0.1:2024",
			Description: "local running server",
		},
	}
	apiClient := langgraphgo.NewAPIClient(configuration)

	t.Run("Test AssistantsAPIService CreateAssistantAssistantsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		assistantsPostRequest := apiClient.AssistantsAPI.CreateAssistantAssistantsPost(context.Background())

		resp, httpRes, err := assistantsPostRequest.Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService DeleteAssistantAssistantsAssistantIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId string

		resp, httpRes, err := apiClient.AssistantsAPI.DeleteAssistantAssistantsAssistantIdDelete(context.Background(), assistantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService GetAssistantAssistantsAssistantIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId string

		resp, httpRes, err := apiClient.AssistantsAPI.GetAssistantAssistantsAssistantIdGet(context.Background(), assistantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService GetAssistantGraphAssistantsAssistantIdGraphGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId langgraphgo.GetAssistantGraphAssistantsAssistantIdGraphGetAssistantIdParameter

		resp, httpRes, err := apiClient.AssistantsAPI.GetAssistantGraphAssistantsAssistantIdGraphGet(context.Background(), assistantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService GetAssistantSchemasAssistantsAssistantIdSchemasGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId string

		resp, httpRes, err := apiClient.AssistantsAPI.GetAssistantSchemasAssistantsAssistantIdSchemasGet(context.Background(), assistantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService GetAssistantSubgraphsAssistantsAssistantIdSubgraphsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId string

		resp, httpRes, err := apiClient.AssistantsAPI.GetAssistantSubgraphsAssistantsAssistantIdSubgraphsGet(context.Background(), assistantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService GetAssistantSubgraphsAssistantsAssistantIdSubgraphsNamespaceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId string
		var namespace string

		resp, httpRes, err := apiClient.AssistantsAPI.GetAssistantSubgraphsAssistantsAssistantIdSubgraphsNamespaceGet(context.Background(), assistantId, namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService GetAssistantVersionsAssistantsAssistantIdVersionsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId string

		resp, httpRes, err := apiClient.AssistantsAPI.GetAssistantVersionsAssistantsAssistantIdVersionsGet(context.Background(), assistantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService PatchAssistantAssistantsAssistantIdPatch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId string

		resp, httpRes, err := apiClient.AssistantsAPI.PatchAssistantAssistantsAssistantIdPatch(context.Background(), assistantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService SearchAssistantsAssistantsSearchPost", func(t *testing.T) {

		// t.Skip("skip test") // remove to run test

		searchAssistant := apiClient.AssistantsAPI.SearchAssistantsAssistantsSearchPost(context.Background())
		assistantSearchRequest := searchAssistant.AssistantSearchRequest(langgraphgo.AssistantSearchRequest{})

		resp, httpRes, err := assistantSearchRequest.Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssistantsAPIService SetLatestAssistantVersionAssistantsAssistantIdVersionsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assistantId string

		resp, httpRes, err := apiClient.AssistantsAPI.SetLatestAssistantVersionAssistantsAssistantIdVersionsPost(context.Background(), assistantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
