/*
LangGraph Platform

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package langgraphgo

import (
	"encoding/json"
)

// checks if the Config type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Config{}

// Config struct for Config
type Config struct {
	Tags []string `json:"tags,omitempty"`
	RecursionLimit *int32 `json:"recursion_limit,omitempty"`
	Configurable map[string]interface{} `json:"configurable,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Config Config

// NewConfig instantiates a new Config object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfig() *Config {
	this := Config{}
	return &this
}

// NewConfigWithDefaults instantiates a new Config object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigWithDefaults() *Config {
	this := Config{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Config) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Config) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Config) SetTags(v []string) {
	o.Tags = v
}

// GetRecursionLimit returns the RecursionLimit field value if set, zero value otherwise.
func (o *Config) GetRecursionLimit() int32 {
	if o == nil || IsNil(o.RecursionLimit) {
		var ret int32
		return ret
	}
	return *o.RecursionLimit
}

// GetRecursionLimitOk returns a tuple with the RecursionLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetRecursionLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.RecursionLimit) {
		return nil, false
	}
	return o.RecursionLimit, true
}

// HasRecursionLimit returns a boolean if a field has been set.
func (o *Config) HasRecursionLimit() bool {
	if o != nil && !IsNil(o.RecursionLimit) {
		return true
	}

	return false
}

// SetRecursionLimit gets a reference to the given int32 and assigns it to the RecursionLimit field.
func (o *Config) SetRecursionLimit(v int32) {
	o.RecursionLimit = &v
}

// GetConfigurable returns the Configurable field value if set, zero value otherwise.
func (o *Config) GetConfigurable() map[string]interface{} {
	if o == nil || IsNil(o.Configurable) {
		var ret map[string]interface{}
		return ret
	}
	return o.Configurable
}

// GetConfigurableOk returns a tuple with the Configurable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetConfigurableOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Configurable) {
		return map[string]interface{}{}, false
	}
	return o.Configurable, true
}

// HasConfigurable returns a boolean if a field has been set.
func (o *Config) HasConfigurable() bool {
	if o != nil && !IsNil(o.Configurable) {
		return true
	}

	return false
}

// SetConfigurable gets a reference to the given map[string]interface{} and assigns it to the Configurable field.
func (o *Config) SetConfigurable(v map[string]interface{}) {
	o.Configurable = v
}

func (o Config) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Config) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.RecursionLimit) {
		toSerialize["recursion_limit"] = o.RecursionLimit
	}
	if !IsNil(o.Configurable) {
		toSerialize["configurable"] = o.Configurable
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Config) UnmarshalJSON(data []byte) (err error) {
	varConfig := _Config{}

	err = json.Unmarshal(data, &varConfig)

	if err != nil {
		return err
	}

	*o = Config(varConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tags")
		delete(additionalProperties, "recursion_limit")
		delete(additionalProperties, "configurable")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfig struct {
	value *Config
	isSet bool
}

func (v NullableConfig) Get() *Config {
	return v.value
}

func (v *NullableConfig) Set(val *Config) {
	v.value = val
	v.isSet = true
}

func (v NullableConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfig(val *Config) *NullableConfig {
	return &NullableConfig{value: val, isSet: true}
}

func (v NullableConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


