/*
LangGraph Platform

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package langgraphgo

import (
	"encoding/json"
	"fmt"
)

// checks if the StoreDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreDeleteRequest{}

// StoreDeleteRequest Request to delete an item.
type StoreDeleteRequest struct {
	// A list of strings representing the namespace path.
	Namespace []string `json:"namespace,omitempty"`
	// The unique identifier for the item.
	Key string `json:"key"`
	AdditionalProperties map[string]interface{}
}

type _StoreDeleteRequest StoreDeleteRequest

// NewStoreDeleteRequest instantiates a new StoreDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreDeleteRequest(key string) *StoreDeleteRequest {
	this := StoreDeleteRequest{}
	this.Key = key
	return &this
}

// NewStoreDeleteRequestWithDefaults instantiates a new StoreDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreDeleteRequestWithDefaults() *StoreDeleteRequest {
	this := StoreDeleteRequest{}
	return &this
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *StoreDeleteRequest) GetNamespace() []string {
	if o == nil || IsNil(o.Namespace) {
		var ret []string
		return ret
	}
	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreDeleteRequest) GetNamespaceOk() ([]string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *StoreDeleteRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given []string and assigns it to the Namespace field.
func (o *StoreDeleteRequest) SetNamespace(v []string) {
	o.Namespace = v
}

// GetKey returns the Key field value
func (o *StoreDeleteRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *StoreDeleteRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *StoreDeleteRequest) SetKey(v string) {
	o.Key = v
}


func (o StoreDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	toSerialize["key"] = o.Key

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StoreDeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varStoreDeleteRequest := _StoreDeleteRequest{}

	err = json.Unmarshal(data, &varStoreDeleteRequest)

	if err != nil {
		return err
	}

	*o = StoreDeleteRequest(varStoreDeleteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStoreDeleteRequest struct {
	value *StoreDeleteRequest
	isSet bool
}

func (v NullableStoreDeleteRequest) Get() *StoreDeleteRequest {
	return v.value
}

func (v *NullableStoreDeleteRequest) Set(val *StoreDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreDeleteRequest(val *StoreDeleteRequest) *NullableStoreDeleteRequest {
	return &NullableStoreDeleteRequest{value: val, isSet: true}
}

func (v NullableStoreDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


