/*
LangGraph Platform

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package langgraphgo

import (
	"encoding/json"
	"fmt"
)


// RunCreateStatefulAssistantId The assistant ID or graph name to run. If using graph name, will default to first assistant created from that graph.
type RunCreateStatefulAssistantId struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RunCreateStatefulAssistantId) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(RunCreateStatefulAssistantId)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RunCreateStatefulAssistantId) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableRunCreateStatefulAssistantId struct {
	value *RunCreateStatefulAssistantId
	isSet bool
}

func (v NullableRunCreateStatefulAssistantId) Get() *RunCreateStatefulAssistantId {
	return v.value
}

func (v *NullableRunCreateStatefulAssistantId) Set(val *RunCreateStatefulAssistantId) {
	v.value = val
	v.isSet = true
}

func (v NullableRunCreateStatefulAssistantId) IsSet() bool {
	return v.isSet
}

func (v *NullableRunCreateStatefulAssistantId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunCreateStatefulAssistantId(val *RunCreateStatefulAssistantId) *NullableRunCreateStatefulAssistantId {
	return &NullableRunCreateStatefulAssistantId{value: val, isSet: true}
}

func (v NullableRunCreateStatefulAssistantId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunCreateStatefulAssistantId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


