/*
LangGraph Platform

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package langgraphgo

import (
	"encoding/json"
)

// checks if the AssistantSearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssistantSearchRequest{}

// AssistantSearchRequest Payload for listing assistants.
type AssistantSearchRequest struct {
	// Metadata to filter by. Exact match filter for each KV pair.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// The ID of the graph to filter by. The graph ID is normally set in your langgraph.json configuration.
	GraphId *string `json:"graph_id,omitempty"`
	// The maximum number of results to return.
	Limit *int32 `json:"limit,omitempty"`
	// The number of results to skip.
	Offset *int32 `json:"offset,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AssistantSearchRequest AssistantSearchRequest

// NewAssistantSearchRequest instantiates a new AssistantSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantSearchRequest() *AssistantSearchRequest {
	this := AssistantSearchRequest{}
	var limit int32 = 10
	this.Limit = &limit
	var offset int32 = 0
	this.Offset = &offset
	return &this
}

// NewAssistantSearchRequestWithDefaults instantiates a new AssistantSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantSearchRequestWithDefaults() *AssistantSearchRequest {
	this := AssistantSearchRequest{}
	var limit int32 = 10
	this.Limit = &limit
	var offset int32 = 0
	this.Offset = &offset
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AssistantSearchRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantSearchRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AssistantSearchRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *AssistantSearchRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetGraphId returns the GraphId field value if set, zero value otherwise.
func (o *AssistantSearchRequest) GetGraphId() string {
	if o == nil || IsNil(o.GraphId) {
		var ret string
		return ret
	}
	return *o.GraphId
}

// GetGraphIdOk returns a tuple with the GraphId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantSearchRequest) GetGraphIdOk() (*string, bool) {
	if o == nil || IsNil(o.GraphId) {
		return nil, false
	}
	return o.GraphId, true
}

// HasGraphId returns a boolean if a field has been set.
func (o *AssistantSearchRequest) HasGraphId() bool {
	if o != nil && !IsNil(o.GraphId) {
		return true
	}

	return false
}

// SetGraphId gets a reference to the given string and assigns it to the GraphId field.
func (o *AssistantSearchRequest) SetGraphId(v string) {
	o.GraphId = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *AssistantSearchRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantSearchRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *AssistantSearchRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *AssistantSearchRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *AssistantSearchRequest) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantSearchRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *AssistantSearchRequest) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *AssistantSearchRequest) SetOffset(v int32) {
	o.Offset = &v
}

func (o AssistantSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssistantSearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.GraphId) {
		toSerialize["graph_id"] = o.GraphId
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssistantSearchRequest) UnmarshalJSON(data []byte) (err error) {
	varAssistantSearchRequest := _AssistantSearchRequest{}

	err = json.Unmarshal(data, &varAssistantSearchRequest)

	if err != nil {
		return err
	}

	*o = AssistantSearchRequest(varAssistantSearchRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "graph_id")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "offset")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssistantSearchRequest struct {
	value *AssistantSearchRequest
	isSet bool
}

func (v NullableAssistantSearchRequest) Get() *AssistantSearchRequest {
	return v.value
}

func (v *NullableAssistantSearchRequest) Set(val *AssistantSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantSearchRequest(val *AssistantSearchRequest) *NullableAssistantSearchRequest {
	return &NullableAssistantSearchRequest{value: val, isSet: true}
}

func (v NullableAssistantSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


