/*
LangGraph Platform

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package langgraphgo

import (
	"encoding/json"
	"fmt"
)


// InterruptAfter Nodes to interrupt immediately after they get executed.
type InterruptAfter struct {
	ArrayOfString *[]string
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *InterruptAfter) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ArrayOfString
	err = json.Unmarshal(data, &dst.ArrayOfString);
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			return nil // data stored in dst.ArrayOfString, return on the first match
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(InterruptAfter)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InterruptAfter) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableInterruptAfter struct {
	value *InterruptAfter
	isSet bool
}

func (v NullableInterruptAfter) Get() *InterruptAfter {
	return v.value
}

func (v *NullableInterruptAfter) Set(val *InterruptAfter) {
	v.value = val
	v.isSet = true
}

func (v NullableInterruptAfter) IsSet() bool {
	return v.isSet
}

func (v *NullableInterruptAfter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterruptAfter(val *InterruptAfter) *NullableInterruptAfter {
	return &NullableInterruptAfter{value: val, isSet: true}
}

func (v NullableInterruptAfter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterruptAfter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


