/*
LangGraph Platform

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package langgraphgo

import (
	"encoding/json"
	"fmt"
)


// Values1 The values to update the state with.
type Values1 struct {
	ArrayOfMapmapOfStringAny *[]map[string]interface{}
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Values1) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into ArrayOfMapmapOfStringAny
	err = json.Unmarshal(data, &dst.ArrayOfMapmapOfStringAny);
	if err == nil {
		jsonArrayOfMapmapOfStringAny, _ := json.Marshal(dst.ArrayOfMapmapOfStringAny)
		if string(jsonArrayOfMapmapOfStringAny) == "{}" { // empty struct
			dst.ArrayOfMapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.ArrayOfMapmapOfStringAny, return on the first match
		}
	} else {
		dst.ArrayOfMapmapOfStringAny = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Values1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Values1) MarshalJSON() ([]byte, error) {
	if src.ArrayOfMapmapOfStringAny != nil {
		return json.Marshal(&src.ArrayOfMapmapOfStringAny)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableValues1 struct {
	value *Values1
	isSet bool
}

func (v NullableValues1) Get() *Values1 {
	return v.value
}

func (v *NullableValues1) Set(val *Values1) {
	v.value = val
	v.isSet = true
}

func (v NullableValues1) IsSet() bool {
	return v.isSet
}

func (v *NullableValues1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValues1(val *Values1) *NullableValues1 {
	return &NullableValues1{value: val, isSet: true}
}

func (v NullableValues1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValues1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


